-- Create table Students

CREATE TABLE STUDENTS (  
ID INT NOT NULL,  
NAME VARCHAR (20) NOT NULL,  
AGE INT NOT NULL,  
ADDRESS CHAR (25),  
PRIMARY KEY (ID)  
);  

--Rename Table 

ALTER TABLE STUDENTS  
RENAME TO STUDENT;  

RENAME STUDENT TO STUDENTS;  

--Alter Table

ALTER TABLE STUDENTS ADD (POSITION CHAR (25), GROUP_NAME CHAR (25));

ALTER TABLE STUDENTS MODIFY POSITION INT;  

ALTER TABLE STUDENTS DROP COLUMN GROUP_NAME; 

ALTER TABLE STUDENTS  
RENAME COLUMN POSITION to POS; 

ALTER TABLE STUDENTS  
RENAME COLUMN ID to ROLL_NO;  

ALTER TABLE STUDENTS  
RENAME COLUMN ADDRESS to CITY;  

ALTER TABLE STUDENTS DROP COLUMN POS; 
  
-- Describe Students table
DESC STUDENTS;

COMMIT;

--Create table Employee

CREATE TABLE Employee  
(  
EmployeeID int,  
FirstName varchar(255),  
LastName varchar(255),  
Email varchar(255),  
AddressLine varchar(255),  
City varchar(255)  
);  

--Create table from another table

CREATE TABLE EmployeeCopy AS  
SELECT EmployeeID, FirstName, Email  
FROM Employee;  

--Drop tables
DROP TABLE STUDENTS;  
DROP TABLE EMPLOYEE;
DROP TABLE EMPLOYEECOPY;

CREATE TABLE STUDENTS (  
ID INT                           NOT NULL,  
NAME VARCHAR (20) NOT NULL,  
AGE INT                         NOT NULL,  
ADDRESS CHAR (25),  
PRIMARY KEY (ID)  
);  

ALTER TABLE STUDENTS  
RENAME COLUMN ID to ROLL_NO;  

ALTER TABLE STUDENTS  
RENAME COLUMN ADDRESS to CITY;  


--INSERT
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (1, 'ABHIRAM', 22, 'ALLAHABAD');  
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (2, 'ALKA', 20, 'GHAZIABAD');  
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (3, 'DISHA', 21, 'VARANASI');  
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (4, 'ESHA', 21, 'DELHI');  
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (5, 'MANMEET', 23, 'JALANDHAR'); 

TRUNCATE TABLE STUDENTS;  

INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (1, 'ABHIRAM', 22, 'ALLAHABAD');  
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (2, 'ALKA', 20, 'GHAZIABAD');  
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (3, 'DISHA', 21, 'VARANASI');  
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (4, 'ESHA', 21, 'DELHI');  
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (5, 'MANMEET', 23, 'JALANDHAR');

DELETE FROM STUDENTS;

INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (1, 'ABHIRAM', 22, 'ALLAHABAD');  
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (2, 'ALKA', 20, 'GHAZIABAD');  
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (3, 'DISHA', 21, 'VARANASI');  
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (4, 'ESHA', 21, 'DELHI');  
INSERT INTO STUDENTS (ROLL_NO, NAME, AGE, CITY)  
VALUES (5, 'MANMEET', 23, 'JALANDHAR');

DELETE FROM STUDENTS WHERE ROLL_NO = 1;

UPDATE STUDENTS SET ROLL_NO= 1, NAME='MANMEET', CITY = 'PATNA' WHERE ROLL_NO = 2;  


SELECT DISTINCT NAME FROM STUDENTS;

SELECT * FROM STUDENTS WHERE ROLL_NO BETWEEN 2 and 4;

SELECT * FROM STUDENTS WHERE NOT ROLL_NO = 2;

SELECT COUNT(*) FROM STUDENTS;
SELECT COUNT(NAME) FROM STUDENTS;
SELECT COUNT(DISTINCT NAME) FROM STUDENTS;

SELECT NAME FROM STUDENTS WHERE ROWNUM <= 2;
SELECT NAME FROM STUDENTS WHERE ROLL_NO = (SELECT MAX(ROLL_NO) FROM STUDENTS);

SELECT NAME FROM (SELECT NAME FROM STUDENTS ORDER BY dbms_random.value) WHERE rownum = 1 ;

SELECT *  FROM STUDENTS WHERE NAME IN ( 'MANMEET' , 'DISHA');  
SELECT * FROM students WHERE name LIKE '%MANMEET';
SELECT * FROM students WHERE name LIKE '_MANMEET';
SELECT * FROM students WHERE name LIKE '_ISH%';
SELECT * FROM students WHERE name LIKE '__ISH%';

SELECT * FROM students order by ROLL_NO OFFSET 1 ROWS FETCH FIRST 1 ROWS ONLY; 
SELECT * FROM students order by ROLL_NO OFFSET 1 ROWS FETCH NEXT 2 ROW ONLY;

SELECT ROLL_NO || '-' || NAME as student FROM STUDENTS;
SELECT ROLL_NO || q'{'s name is }' || NAME as student FROM STUDENTS;

WITH student_temp as (select * from employees)
select * from student_temp;

--UNION & UNION ALL
CREATE TABLE Employee1  
(  
FirstName varchar(255),  
LastName varchar(255)
);

CREATE TABLE Customer  
(  
FirstName varchar(255),  
LastName varchar(255)
); 


INSERT INTO EMPLOYEE1 VALUES('A', 'AB');
INSERT INTO EMPLOYEE1 VALUES('B', 'BC');
INSERT INTO EMPLOYEE1 VALUES('C', 'CD');
INSERT INTO EMPLOYEE1 VALUES('D', 'DA');

INSERT INTO Customer VALUES('D', 'DA');
INSERT INTO Customer VALUES('E', 'EF');
INSERT INTO Customer VALUES('F', 'FG');
INSERT INTO Customer VALUES('G', 'GE');

SELECT * FROM EMPLOYEE1;
SELECT * FROM CUSTOMER;

SELECT * FROM EMPLOYEE1
UNION
SELECT * FROM CUSTOMER;

SELECT * FROM EMPLOYEE1
UNION ALL
SELECT * FROM CUSTOMER;

SELECT * FROM EMPLOYEE1
EXCEPT
SELECT * FROM CUSTOMER;

CREATE TABLE PEOPLE (
    GENDER VARCHAR(255),
    NAME VARCHAR(255),
    CHECK( GENDER IN ('M', 'F', 'U'))
);

INSERT INTO PEOPLE VALUES ('A', 'A');